### ISSUE TITLE
Documentation has a misspelling of inputs required

### ISSUE THREAD

**Issue by donavanbecker** [autosuite/autolog#14]
## The Problem

github-repository was not set as a correct input. Got owner: '' and repo: 'undefined'
##[error]Node run failed with exit code 1

## Reproduction

1. Added to my workflow on donavanbecker/homebridge-honeywell-home

## Expected Output

Create and update Changelog.md

## Environment

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Microsoft Edge
- Version: IDK NEWEST

## Screenshots and Other Context
 Run teaminkling/autologger@master1s
##[error]Node run failed with exit code 1
Run teaminkling/autologger@master
From https://github.com/donavanbecker/homebridge-honeywell-home

```Authenticating with the GitHub API...
 * [new branch]      ResideoAPI -> origin/ResideoAPI
 * [new tag]         v2.3.0     -> v2.3.0
 * [new tag]         v2.3.1     -> v2.3.1
 * [new tag]         v2.3.2     -> v2.3.2
 * [new tag]         v2.3.3     -> v2.3.3
 * [new tag]         v2.4.0     -> v2.4.0
 * [new tag]         v2.5.1     -> v2.5.1
 * [new tag]         v2.5.2     -> v2.5.2
 * [new tag]         v2.6.0     -> v2.6.0
 * [new tag]         v2.6.1     -> v2.6.1
 * [new tag]         v3.0.0     -> v3.0.0
 * [new tag]         v3.0.1     -> v3.0.1
 * [new tag]         v3.0.2     -> v3.0.2
 * [new tag]         v3.0.3     -> v3.0.3
 * [new tag]         v3.0.4     -> v3.0.4
 * [new tag]         v3.0.5     -> v3.0.5
 * [new tag]         v4.0.0     -> v4.0.0
 * [new tag]         v4.0.1     -> v4.0.1
 * [new tag]         v4.0.2     -> v4.0.2
 * [new tag]         v4.0.3     -> v4.0.3
 * [new tag]         v4.0.4     -> v4.0.4
 * [new tag]         v4.1.0     -> v4.1.0
 * [new tag]         v4.1.1     -> v4.1.1
github-repository was not set as a correct input. Got owner: '' and repo: 'undefined'
##[error]Node run failed with exit code 1
```

**Comment by paced** [comment]
Yeah, this is a bug. I'm planning on releasing a major overhaul of the versioning system for every tool in the Autosuite, and will update the `master` version with something that works for your use case.

**Comment by donavanbecker** [comment]
awesome! let me know!

**Comment by paced** [comment]
@donavanbecker For now, please use the explicit `0.1.0` version and tell me how that goes. I'm going to release the next version with fixes and update you whenever that's done.

Ensure `github-token` and `github-repository` uses a hyphen (-) and not an underscore (_). The documentation was wrong, and I'm fixing it - and a bunch of other issues - for the next release.

**Comment by paced** [comment]
Try `autosuite/autolog@5f7402d0ba645a0e5fb01001aca6c300ac5c07a3`. I can't speak for the stability of the `master` branch until `v1.0.0` is released (hopefully soon), but you can _probably_ use it with no problems.

Note: the current versioning of everything in the Autosuite is `x.y.z` e.g.: `0.2.0` (like the next release version) but I will be supporting and moving everything to solely the `vx.y.z` e.g.: `v0.3.0` tag syntax in the future. This means when I delete the old tags for new ones, things might start to break.

I'll try to warn people using it when that happens. For now, please feel free to open a new issue in case you have problems.
